export const DEFAULT_CATEGORY_ICON = 'layers';

export const CATEGORY_ICONS: Readonly<Record<string, string>> = {
	development: 'cpu',
	backend: 'server',
	frontend: 'layout',
	frameworks: 'layers',
	mobile: 'smartphone',
	devops: 'cloud',
	infrastructure: 'server',
	security: 'shield',
	testing: 'check-circle',
	performance: 'activity',
	ai: 'brain',
	'ai-ml': 'brain',
	'ai-agents': 'sparkles',
	'ai-tools': 'wand',
	agents: 'sparkles',
	data: 'database',
	'data-science': 'bar-chart',
	'game-dev': 'gamepad',
	gamedev: 'gamepad',
	'game-dev-llm': 'gamepad',
	blockchain: 'link',
	web3: 'globe',
	finance: 'dollar-sign',
	trading: 'trending-up',
	business: 'briefcase',
	strategy: 'target',
	startup: 'rocket',
	founder: 'lightbulb',
	product: 'box',
	enterprise: 'building',
	marketing: 'megaphone',
	community: 'users',
	communications: 'message-circle',
	creative: 'pen-tool',
	design: 'palette',
	space: 'rocket',
	biotech: 'flask',
	robotics: 'cpu',
	climate: 'globe',
	education: 'graduation-cap',
	legal: 'scale',
	hardware: 'cpu',
	integrations: 'plug',
	integration: 'plug',
	mcp: 'plug',
	'mcp-server': 'plug',
	compliance: 'clipboard',
	architecture: 'layers',
	analytics: 'bar-chart',
	ecommerce: 'shopping-cart',
	nocode: 'wand',
	productivity: 'check-circle',
	engineering: 'wrench',
	methodology: 'compass'
};

export function getCategoryIcon(category: string | null | undefined): string {
	return CATEGORY_ICONS[category?.toLowerCase() ?? ''] ?? DEFAULT_CATEGORY_ICON;
}
