import { mkdirSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import {
	evaluateSkillRecommendations,
	summarizeSkillRecommendationEvals,
	type SkillRecommendationEvalResult
} from '../src/lib/services/skill-recommendation-evals';

const reportJsonPath = resolve('reports/skill-recommendation-eval.json');
const reportMarkdownPath = resolve('reports/skill-recommendation-eval.md');

function percent(value: number): string {
	return `${(value * 100).toFixed(1)}%`;
}

function ids(value: string[] | string[][]): string {
	if (value.length === 0) return '-';
	if (Array.isArray(value[0])) {
		return (value as string[][]).map((group) => `[${group.join(' | ')}]`).join(', ');
	}
	return (value as string[]).join(', ');
}

function markdown(results: SkillRecommendationEvalResult[]): string {
	const summary = summarizeSkillRecommendationEvals(results);
	const lines = [
		'# Skill Recommendation Eval',
		'',
		'Generated by `npx tsx scripts/evaluate-skill-recommendations.ts` from the shared golden recommendation cases.',
		'',
		'## Summary',
		'',
		`- Cases: ${summary.caseCount}`,
		`- Passed: ${summary.passCount}/${summary.caseCount} (${percent(summary.passRate)})`,
		`- Average score: ${summary.averageScore.toFixed(3)}`,
		`- Average labeled precision@10: ${percent(summary.averageLabeledPrecisionAtK)}`,
		`- Average required recall: ${percent(summary.averageRequiredRecall)}`,
		`- Average any-of recall: ${percent(summary.averageAnyOfRecall)}`,
		`- Must-not clean rate: ${percent(summary.averageMustNotCleanRate)}`,
		'',
		'## Cases',
		'',
		'| Case | Pass | Score | Precision@10 | Required Recall | Any-Of Recall | Must-Not Clean | Missing | Unwanted |',
		'| --- | --- | ---: | ---: | ---: | ---: | ---: | --- | --- |',
		...results.map((result) => [
			result.name,
			result.pass ? 'yes' : 'no',
			result.score.toFixed(3),
			percent(result.labeledPrecisionAtK),
			percent(result.requiredRecall),
			percent(result.anyOfRecall),
			percent(result.mustNotCleanRate),
			ids([...result.missingRequired, ...result.missingAnyOf.map((group) => `[${group.join(' | ')}]`)]),
			ids(result.unwanted)
		].join(' | ')).map((row) => `| ${row} |`),
		'',
		'## Top Recommendations',
		'',
		...results.flatMap((result) => [
			`### ${result.name}`,
			'',
			`Prompt: ${result.prompt}`,
			'',
			`Top skills: ${result.ids.join(', ')}`,
			''
		])
	];
	return `${lines.join('\n')}\n`;
}

const results = evaluateSkillRecommendations();
const summary = summarizeSkillRecommendationEvals(results);
const payload = { summary, results };

mkdirSync(dirname(reportJsonPath), { recursive: true });
writeFileSync(reportJsonPath, `${JSON.stringify(payload, null, 2)}\n`);
writeFileSync(reportMarkdownPath, markdown(results));

console.log(`Skill recommendation eval: ${summary.passCount}/${summary.caseCount} passed`);
console.log(`Average score: ${summary.averageScore.toFixed(3)}`);
console.log(`Average labeled precision@10: ${percent(summary.averageLabeledPrecisionAtK)}`);
console.log(`Report: ${reportMarkdownPath}`);

if (summary.failures.length > 0) {
	console.error(`Failures: ${summary.failures.join(', ')}`);
	process.exit(1);
}
